### ISSUE TITLE
Prepare code for production

### ISSUE THREAD

**Issue by hgwood** [Zenika/intranet-zenika-academy#6]
Subtask of https://github.com/Zenika/dreamlab/issues/203

- [X] Enable database configuration by env vars (see #1)
- [X] Merge backend and frontend repos (see #2)
- [x] Change frontend to call the API on `/api` instead of `http://localhost:4000/api` (configure a proxy on the frontend server to make it work in dev) (done as part of #3)
- [x] Format with prettier (see #8)
- [x] Ensure user email unicity using database constraint instead of read-then-write (see #12)
- [x] Make default passwords configurable, but ensure strong in production (see #13)
- [x] Redirect to HTTPS in production (see #15)
